name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build Project
        run: |
          # Comandos para compilar seu projeto
          # Exemplo: mvn clean install

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          # Execute a análise do SonarQube
          # Substitua as informações de URL do SonarQube e projeto
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io/project/overview?id=luana-fs_backend-challenge \
            -Dsonar.projectKey=luana-fs_backend-challenge
