name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Install SonarScanner
        run: |
          curl -o sonarscanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
          unzip sonarscanner-cli.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.6.0.2311-linux/bin
    
      - name: Build Project
        run: |
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io/project/overview?id=luana-fs_backend-challenge \
            -Dsonar.projectKey=luana-fs_backend-challenge
