name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.8
        with:
          organization: "sua-organizacao"
          projectKey: myfirstproject
          token: ${{ secrets.SONARQUBE }}
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Project
        run: |
      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io/project/overview?id=luana-fs_backend-challenge \
            -Dsonar.projectKey=luana-fs_backend-challenge \
            -Dsonar.scanner.metadataFilePath=sonar-project.properties
